### ISSUE TITLE
DLTKCore.DEBUG is always true

### ISSUE THREAD

**Issue by rombert** [eclipse-dltk/dltk.core#1]
https://github.com/eclipse-dltk/dltk.core/blob/4b113e2a6f229757d1b35f6d208048c1468ecdf3/core/plugins/org.eclipse.dltk.core/model/org/eclipse/dltk/core/DLTKCore.java#L72-L73

This leads to https://github.com/eclipse-dltk/dltk.core/blob/4b113e2a6f229757d1b35f6d208048c1468ecdf3/core/plugins/org.eclipse.dltk.core/model/org/eclipse/dltk/internal/core/DeltaProcessor.java#L1531 always being active and printed on the console.

It would be very nice to not have printed on the Console since it's not useful for regular users and also a bit confusing.

**Comment by akurtakov** [comment]
Unfortunately, since the move to github(https://www.eclipse.org/lists/dltk-dev/msg02661.html)  no one stepped up to recover builds (https://ci.eclipse.org/dltk/) and I see this as a prereq for anything else to happen. 
If/when someone recovers builds , we will be more than happy to review a PR fixing your issue. 
Maybe you would like to give it a try as you seem to still use the project while many have moved to other solutions (LS-based).

**Comment by rombert** [comment]
Thanks for the additional context @akurtakov . I reviewed my Eclipse setup and noticed that I had the PHP Development Tools feature installed, which brought in DLTK. Since I don't use PDT anymore I uninstalled both and my problem is now solved.

**Comment by akurtakov** [comment]
I'll close this one but if anyone comes to same/similar issue please consider starting from the work in my previous comment to get builds working before looking at anything else.
